package com.bid.app.interfaces;

public interface IBundle {

    String BUNDLE_EMAIL = "EMAIL";
    String BUNDLE_MOBILE_NUMBER = "MOBILE_NUMBER";
    String BUNDLE_CODE = "CODE";
    String BUNDLE_FRAGMENT_FROM = "FRAGMENT_FROM";
    String BUNDLE_TEST_DATE = "TEST_DATE";
    String BUNDLE_TEST_TIME = "TEST_TIME";
    String BUNDLE_TEST_LOCATION = "TEST_LOCATION";
    String BUNDLE_TEST_TYPE = "TEST_TYPE";
    String BUNDLE_TEST_STATUS_NAME = "test_status_name";
    String BUNDLE_TEST_STATUS_COLOR = "test_color";
    String BUNDLE_TEST_STATUS_FONT_COLOR = "font_color";
    String BUNDLE_TEST_STATUS = "TEST_STATUS";
    String BUNDLE_SELECTED_PERSONAL_DETAILS = "SELECTED_PERSONAL_DETAILS";
    String BUNDLE_COUNTRY_OBJECT = "COUNTRY_OBJECT";
    String BUNDLE_DOCUMENT_ID_OBJECT = "DOCUMENT_ID";
    String BUNDLE_ROUTE_TICKETS = "ROUTE_TICKETS";
    String BUNDLE_TRIP_ID = "TRIP_ID";
    String BUNDLE_CARD_LIST_INFO = "CARD_LIST_INFO";
    String BUNDLE_SEAT_NUMBER = "SEAT_NUMBER";
    String BUNDLE_BUS_ID = "BUS_ID";
    String BUNDLE_DRIVER_ID = "DRIVER_ID";
    String BUNDLE_FAMILY_MEMBER = "FAMILY_MEMBER";
    String BUNDLE_TICKET = "BUNDLE_TICKET";
    String BUNDLE_ROUTE = "ROUTE";
    String BUNDLE_TICKETS = "BUNDLE_TICKETS";
    String BUNDLE_PASSENGER = "PASSENGER";
    String BUNDLE_IS_UPCOMING = "IS_UP_COMING";
    String BUNDLE_STATUS_RESPONSE = "STATUS_RESPONSE";
}
